redis01:
    build: .
    ports:
     - 7001:6379
    volumes:
     - .:/config
    environment:
     - REDIS_NODE=01
redis02:
    build: .
    ports:
     - 7002:6379
    volumes:
     - .:/config
    environment:
     - REDIS_NODE=02
redis03:
    build: .
    ports:
     - 7003:6379
    volumes:
     - .:/config
    environment:
     - REDIS_NODE=03
redis04:
    build: .
    ports:
     - 7004:6379
    volumes:
     - .:/config
    environment:
     - REDIS_NODE=04
redis05:
    build: .
    ports:
     - 7005:6379
    volumes:
     - .:/config
    environment:
     - REDIS_NODE=05
redis06:
    build: .
    ports:
     - 7006:6379
    volumes:
     - .:/config
    environment:
     - REDIS_NODE=06

