version: '2'

services:
    redis:
        image: "redis:3.0.7"

        volumes:
            - /data/redis:/data/redis:rw
    
        network_mode: "host"
        
        mem_limit: 2048m

        ports:
            - "6379:6379"

        environment:
            affinity: container!=*redis*"
            SERVICE_NAME: redis
        labels:
            - "net.dlatv.mfwk.name=redis"

    redis-trib:
        build: "redis-trib/"

